bug: [PagoPa-2166] - fix list info for cart
pagopa/pagopa-biz-events-service pull request #93
Opened 2024-09-24 08:55 UTC by alessio-acitelli

#### List of Changes

- fixed id value
- fixed payeeName e payeeTaxCode value
- fixed amount value
- fixed junit tests

#### Motivation and Context

- error reporting by users of the service

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-24 12:19 UTC, pasqualespica requested changes

2024-09-24 12:19 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
> +        /*
ok remove it

2024-09-24 12:19 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
> +    /*
ok remove it

2024-09-24 12:19 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
> +                .transactionId(viewUser.getId().replace("-p", "").replace("-d", "")) // eventId stripped of the -d or -p suffix
directly remove the last 2 characters.
The replace, in addition to being done twice, may not be safe if that character exists within the Id.
and just leave the comment that explains and gives context

2024-09-24 12:19 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
> +            String eventId = viewUser.getId().replace("-p", "").replace("-d", "");
see above comment

2024-09-24 12:19 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
> +            /*
remove it

2024-09-24 12:38 UTC, alessio-acitelli commented on src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
> +        /*
done

2024-09-25 07:37 UTC, pasqualespica approved these changes
🚀

2024-09-25 07:38 UTC, merged